source 'https://rubygems.org'

gemspec

# Add debugger for pry that's compatible with 0.10.4
gem 'pry-nav', git: 'https://github.com/nixme/pry-nav.git', branch: 'master'
# This file was generated by Appraisal

# TODO for only testing only, remove me
# gem "pry-nav", git: "https://github.com/nixme/pry-nav.git", branch: "master"
# gem "rails", "~> 6.0.0"
# gem "mysql2", "< 0.5", platform: :ruby